logging:
    level:
        org.springframework.web: DEBUG

server:
    port: 8080

app:
    jwtSecret: "asdffdsa"
    jwtExpirationInMs: 604800000

spring:
    data:
        mongodb:
            database: sso

management.health.db.enabled: true
management.health.mongo.enabled: true